<?php
include_once './../connection.php';
session_start();

if(!$_SESSION['username'])
{
	header('Location: index.php');
}

$qry = "select * from contacts where id = " .$_REQUEST['hidid'];
$rs = mysql_query($qry);  
$row = mysql_fetch_assoc($rs);

$to = $row['email'];
$subject = "Your Query on Bhanwari Devi Trust Matrimonial";
$txt = "<html><body><span style='color:#FF0000;'>Your Answer is </span><span style='color:#009900;'>". $_REQUEST['ans'] . "</span><br><span style='color:#000000;font-weight:bold'>Please Do not reply. This is a autogenerated mail.</span></body></html>";
$headers = "From: info@bhawanridevitrust.rbbs.in\r\nReply-To: info@bhawanridevitrust.rbbs.in\r\n";
$headers .= "Content-type: text/html\r\n"; 

$mail_sent = @mail($to,$subject,$txt,$headers);
$query="update contacts set ans_state = 1 where id = " .$_REQUEST['hidid'];
mysql_query($query);
$_SESSION['last_error_id'] = 32;

header("Location: query.php?hidrecstart=".$_REQUEST["hidrecstart"]);
?>
